Targil ping
hadar759/general-discord-bot pull request #1
Opened 2020-08-06 14:35 UTC by hadar759

I think i'm finished :3

2020-08-06 15:15 UTC, tomgrin10 requested changes
התחלתי

2020-08-06 15:15 UTC, tomgrin10 commented on discord-bot/Commands/ICommand.cs
> +        Task Handle(DSharpPlus.Entities.DiscordMessage msg);
תשתמש בusing אחי
using DSharpPlus.Entities
בכל המקומות שבהם אתה עושה דברים דומים

2020-08-06 15:15 UTC, tomgrin10 commented on discord-bot/Commands/ISortCommand.cs
> +namespace discord_bot.Commands
אחי שמות פרוייקטים בסי שארפ וnamespaceים הם lower case??

2020-08-06 15:15 UTC, tomgrin10 commented on discord-bot/Commands/ICommand.cs
> +        Task Handle(DSharpPlus.Entities.DiscordMessage msg);
אולי השם run יותר מתאים לפונקציה, אתה לא עושה פה handle למשהו, אתה **מריץ** פקודה

2020-08-06 15:15 UTC, tomgrin10 commented on discord-bot/Commands/ICommand.cs
> +    interface ICommand
פצצה של אינטרפייס

2020-08-06 15:15 UTC, tomgrin10 commented on discord-bot/Commands/ISortCommand.cs
> +    interface ISortCommand
אינטרפייס לא מגדיר פעולה, אלא יכולת.
במקום הפועל Sort אולי עדיף Sorter?

2020-08-06 15:15 UTC, tomgrin10 commented on discord-bot/Commands/SortCommand.cs
> +    class SortCommand: ISortCommand
אז האינטרפייס הזה עושה מלא דברים, בואו נפרט ילדים:
1. מפרסר את ההודעה ומפרק אותה לחלקים
2. מחפש את הפקודה המתאימה להריץ מתוך הפקודות
3. מריץ את הפקודה

שאלה: אם אני רוצה לפרק את ההודעה לחלקים שלה בשביל לדעת מה הפרמטר השני שהיא קיבלה?

2020-08-06 15:22 UTC, hadar759 commented on discord-bot/Commands/ICommand.cs
> +        Task Handle(DSharpPlus.Entities.DiscordMessage msg);
אבל בעתיד אולי לא אעשה ראן לדברים, אלא פשוט אטפל בהם בלי להריץ כלום

2020-08-06 15:25 UTC, hadar759 commented on discord-bot/Commands/SortCommand.cs
> +    class SortCommand: ISortCommand
זה לא מריץ את הפקודה זה שולח אותה למחלקה להריץ אותה, עם ההודעה עצמה בשביל קונטקסט
ואני מבין מה אתה אומר, להגנתי יאמר ששאר הפרמטרים זה שאר הטקסט וכאן אני רק מחפש את הפקודה עצמה בשביל לעשות לה פורוורד, אבל כן אחרי זה אם אצטרך את שאר הטקסט אצטרך עוד פעם לפרק אותה במחלקה אחרת וזה סתם חבל

2020-08-07 15:15 UTC, tomgrin10 approved these changes

2020-08-07 15:15 UTC, merged